compose:
  active: true
  ModifierHeightWithText:
    active: true
  ReusedModifierInstance:
    active: true
  PublicComposablePreview:
    active: true
  ComposableEventParameterNaming:
    active: false
  UnnecessaryEventHandlerParameter:
    active: true
    reportConstantArguments: true
  ComposableParametersOrdering:
    active: true
    trailingSlotNames: [ 'content' ]
  ModifierDefaultValue:
    active: true
  MissingModifierDefaultValue:
    active: true
  TopLevelComposableFunctions:
    active: false
    allowInObjects: false
    allowInInterfaces: false
  ComposableFunctionName:
    active: true
  ConditionCouldBeLifted:
    active: false
    ignoreCallsWithArgumentNames: [ 'modifier' ]
  UnnecessaryLayoutWrapper:
    active: false
